### ISSUE TITLE
Product categorization

### ISSUE THREAD

**Issue by auth2b** [awkale/prn_product#2]
Please segment products:

Product category (US wire distribution, microlists, etc.)
Product line (National, Top Markets, Regional, State, Local, Policy, Features, Other, Web-only)
Product (what you already have)

Within the product listing (in the product line), it should be alphabetized.

**Comment by awkale** [comment]
Product line: service description in excel (col C)

**Comment by awkale** [comment]
National == PREMIUM & US2 (in excel)

**Comment by awkale** [comment]
moved to https://prnewswire.jira.com/browse/PRND-5
